### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by hiagoptk** [hiagoptk/todo-app-rocketseat-ignite#2]
## Users related task

 - [x] Users should be able to create a new user
 - [x] Users should not be able to create a new user when username already exists
 
## Todos related task

- [x] Todos should be able to list all user's todo

- [x]  Todos should be able to create a new todo
- [x]  Todos should be able to update a todo
- [x]  Todos should not be able to update a non existing todo
- [x]  Todos should be able to mark a todo as done
- [x]  Todos should not be able to mark a non existing todo as done
- [x]  Todos should be able to delete a todo
- [x]  Todos should not be able to delete a non existing todo
